# Generated by Django 5.2.11 on 2026-06-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=200)),
                ('data', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
